main: dev.paracausal.testplugin.TestPlugin
name: TestPlugin
version: 1.0.0
api-version: 1.20
author: Mantice

commands:
  currency:
    description: 'Manipulate a player''s currency!'
    usage: '/currency <add/remove/set> <amount>'